#!/usr/bin/bash
# a simple shell script to setuo dev env in a clean linux (ubuntu)

# update packages repositories
apt-get update
# upgrade packages
apt-get upgrade

# installing my dev packages
# git
apt-get install git --assume-yes
# tree
apt-get install tree --assume-yes
# neofitch
apt install neofetch --assume-yes
# fortune
apt-get install fortune-mod --assume-yes
# fish
apt-get install fish --assume-yes
# gcc
apt-get install gcc --assume-yes
# gh
apt-get install gh --assume-yes
# nginx
apt-get install nginx-core --assume-yes
# nodejs
apt-get install nodejs --assume-yes
# puppet
apt-get install puppet --assume-yes
# python3
apt-get install python3 --assume-yes
# pycodestyle
apt-get install pycodestyle --assume-yes
# Shellcheck
apt-get install shellcheck --assume-yes
# Code
apt-get install code --assume-yes
# curl
apt-get install curl --assume-yes
# betty
git clone https://github.com/alx-tools/Betty.git ~/Betty
~/Betty/install.sh
rm -drf Betty/


# copy config folder
mkdir -p ~/.config/fish/functions/
cp -f -R config.fish ~/.config

# copy .gitconfig file
cp ./.gitconfig ~

# make fish default shell
chsh -s /usr/bin/fish
